### ISSUE TITLE
circle is different to your actual examples

### ISSUE THREAD

**Issue by lewislepton** [FuzzyWuzzie/headbutt#2]
just learning a bit on GJK & the such. but looking at the code & even trying to run it. it just errors with the `Circle`, due to it not having 2 values needed, but the examples show 2

thanks

**Comment by lewislepton** [comment]
the circle does not have things like the centre, as what it would do in the examples & even the built examples to look at & preview

**Comment by lewislepton** [comment]
ahhh ive noticed whats been done. is that some things have been updated, but with something like the offset, which originally was the centre, its not been updated

**Comment by hamaluik** [comment]
Yea, sorry, the repo is a bit of a mess right now as I was playing with how best to implement things. I've tended to end up defining custom classes which extend Shapes to do what's necessary and I think accidentally committed thing I never meant to / things are half-baked. I'll try to clean things up soon.
