### ISSUE TITLE
how could you rotate objects?

### ISSUE THREAD

**Issue by lewislepton** [FuzzyWuzzie/headbutt#3]
as the title says. how could you go about rotating the objects as well, keeping the shape & making sure its actually rotating?

thanks again for this library. very lovely

**Comment by hamaluik** [comment]
The easiest way would be to apply a matrix transformation to the points. This goes back to my comment in #2 about decided how best to provide an API for this.

Essentially, when you define a shape, you're defining its points in global coordinates. So the function

```haxe
public function support(direction:Vec2):Vec2;
```

Has to give the support point (in global coordinates) in the given (global) direction. To support translating and rotating then, much as you might apply a model matrix to an object's vertices when rendering to place its pixels in the correct location, you would apply a model matrix to the shape's vertices when testing to test them in the correct location.

So for example, you could write a `Square` which rotates as:

```haxe
// extremely unoptimized, but should work
class Square implements Shape {
    var points:Array<Vec2>; // our points in local space
    var transformation:Mat3; // our "model" matrix

    public var angle(default, set):Float = 0; // the angle we're at
    private function set_angle(a:Float):Float {
        // update the model matrix
        transformation.r0c0 =  Math.cos(a);
        transformation.r0c1 = -Math.sin(a);
        transformation.r1c0 =  Math.sin(a);
        transformation.r1c1 =  Math.cos(a);
        return angle = a;
    }

    public function new(radius:Float=1) {
        // our square has four vertices in each corner
        points = [
            new Vec2(-radius, -radius),
            new Vec2( radius, -radius),
            new Vec2( radius,  radius),
            new Vec2(-radius,  radius),
        ];

        // and starts with no transformation
        transformation = Mat3.identity(new Mat3());
    }

    // apply the model matrix to each local point to transform it
    // into global coordinates
    private function transformed_points():Array<Vec2> {
        return points.map(function(point:Vec2):Vec2 {
            var point:Vec3 = new Vec3(point.x, point.y, 1);
            Mat3.multMat(transformation, point, point);
            return new Vec2(point.x, point.y);
        });
    }

    public function support(direction:Vec2):Vec2 {
        // transform the points first
        // would be better to do this in the `angle` setter
        // so we don't re-do all the calculations for each support
        // function call
        var test_points:Array<Vec2> = transformed_points();

        var furthestDistance:Float = Math.NEGATIVE_INFINITY;
        var furthestVertex:Vec2 = new Vec2(0, 0);

        var vo:Vec2 = new Vec2();
        for(v in test_points) {
            vo = v.addVec(offset, vo);
            var distance:Float = Vec2.dot(vo, direction);
            if(distance > furthestDistance) {
                furthestDistance = distance;
                furthestVertex = vo.copy(furthestVertex);
            }
        }

        return furthestVertex;
    }
}
```

There is an easy way to define this, and my goal was originally to make several pre-created shapes and define much faster and optimized functions for them so you can easily just pick one and use it, or define your own if you need to. Unfortunately I kind of forgot about doing this in the whirlwind of life, but I still think it's worthwhile doing and will re-add it to my list.

Hope that clears up any confusion, and thanks for taking a look! Your Kha tutorials were immensely helpful for me getting started with Kha by the way, so thanks!

**Comment by lewislepton** [comment]
thanks man. really. this helps a lot. this type of collision is fantastic & ive been reading more up on on it & trying more tests.

thanks for the lovely comment on my tutorials. id love to bring this type of collision into it at some point using these methods & all thanks for it will point to this repo & yourself for sharing xxx

**Comment by lewislepton** [comment]
I know this is pretty old. but I did try this & have been trying on & off for a while now.

but one thing that always pops up is this:
![Screenshot 2019-05-23 at 22 58 31](https://user-images.githubusercontent.com/11299322/58289457-6263cd00-7dae-11e9-8305-dbf8a76a9e99.png)

basically the first `point` is stating it needs Matrix3 rather than Vector2. 'I have been editing the libraries into my own engine, that's why they look different, but are the same' ;)

just scratching my head on this. but also looking at other ways I could do this, currently looking at differ for pointers.

thanks again

**Comment by lewislepton** [comment]
I do have things rotating, but more so in the graphics, but not so much in the actual body of the shape.

thanks again

**Comment by hamaluik** [comment]
I'm not sure what's going on in your math library, but I started work on including transformations in headbutt in the [transforms branch](https://github.com/hamaluik/headbutt/tree/transforms) which may be of some help. I haven't touched it in a few months, but I think it hasn't been merged yet because the transforms were buggy in 3D.. not 100% sure on that though.

**Comment by lewislepton** [comment]
Aaah, I have not checked that branch. I'll give it a look-see when I'm at my computer

Cheers bud

**Comment by hamaluik** [comment]
Super late, but in case you're still interested, [v0.5.0](https://github.com/hamaluik/headbutt/releases/tag/v0.5.0) adds support for matrix transforms to all of the provided shapes:

```haxe
var square: Rectangle = new Rectangle(new Vec2(2, 2));
square.setTransform(new Vec2(2.1, 0), Math.PI / 4, new Vec2(1, 1));
```
