### ISSUE TITLE
[QUESTION] is it possible to have concave shape collision

### ISSUE THREAD

**Issue by lewislepton** [FuzzyWuzzie/headbutt#4]
as the question title is. is it possible to have concave shape collision. so collision within shapes that say look like stars?
as a star would have collision shape like a pentagon, but goes inwards for the star shape

**Comment by lewislepton** [comment]
I guess you could do a cheap way of creating shapes that could take the shape of each stars points then have it in a class of its own. maybe

**Comment by hamaluik** [comment]
Sorry for the long delay. Short answer: not easily. Long answer: yes, but you have to break the concave shape into multiple convex shapes using something like [nerik/poly2trihx ](https://github.com/nerik/poly2trihx) and test each of the convex shapes against whatever you're trying to collide against. as far as I understand it, this is just a mathematical reality of calculating collisions this way.
